version: "2.3"
services:
  face3d: &face3d
    build:
      context: .
      dockerfile: Dockerfile
    image: face3d:face3d_main
    environment:
      # Variables for docker_entrypoint.bsh
      - DOCKER_USERNAME=face3d_user
      - DISPLAY
      - MXNET_CUDNN_AUTOTUNE_DEFAULT=0
      - MXNET_ENABLE_GPU_P2P=0
    volumes:
      - type: volume
        source: home
        target: /home/face3d_user
      - type: bind
        source: ..
        target: /face3d
      - type: volume
        source: face3d_build
        target: /face3d/build
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    runtime: nvidia
volumes:
  home:
  face3d_build:
